# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Second norm
#'
#' Calculate second norm of a vertical vector
#'
#'@param x a numeric column vector to calculate the second norm
#'@param p a integer represents the dimension of x
#'@return ||x||_2
norm <- function(x, p) {
    .Call(`_BRIGHT_norm`, x, p)
}

#' Soft-thresholding
#'
#' Calculate the soft-thresholding result
#'
#'@param z a numeric scalar to be soft-thresholded
#'@param l a numeric scalar for the soft-thresholding parameter
#'@return S(z,l)
S <- function(z, l) {
    .Call(`_BRIGHT_S`, z, l)
}

#' Firm-thresholding
#'
#' Calculate the Firm-thresholding result
#'
#'@param z a numeric scalar to be Firm-thresholded
#'@param l1 a numeric scalar for the first Firm-thresholding parameter
#'@param l2 a numeric scalar for the second Firm-thresholding parameter
#'@param gamma a numeric scalar for the third Firm-thresholding parameter
#'@return F(z,l1,l2)
F <- function(z, l1, l2, gamma) {
    .Call(`_BRIGHT_F`, z, l1, l2, gamma)
}

#' SCAD-thresholding
#'
#' Calculate the SCAD-thresholding result
#'
#'@param z a numeric scalar to be SCAD-thresholded
#'@param l1 a numeric scalar for the first SCAD-thresholding parameter
#'@param l2 a numeric scalar for the second SCAD-thresholding parameter
#'@param gamma a numeric scalar for the third SCAD-thresholding parameter
#'@return Fs(z,l1,l2)
Fs <- function(z, l1, l2, gamma) {
    .Call(`_BRIGHT_Fs`, z, l1, l2, gamma)
}

Sigma <- function(X, Sig, tau, P, N) {
    .Call(`_BRIGHT_Sigma`, X, Sig, tau, P, N)
}

gd_gaussian <- function(a, b, Sig, K1, Xtbt, XtY, df, l, P, g, penalty, lam1, lam2, gamma, eta, maxChange) {
    invisible(.Call(`_BRIGHT_gd_gaussian`, a, b, Sig, K1, Xtbt, XtY, df, l, P, g, penalty, lam1, lam2, gamma, eta, maxChange))
}

MaxLambda <- function(XtY, tilde_beta, X, K1, m, K0, tau, eta, alpha, eps, max_iter) {
    .Call(`_BRIGHT_MaxLambda`, XtY, tilde_beta, X, K1, m, K0, tau, eta, alpha, eps, max_iter)
}

gdfit_gaussian <- function(XtY, tilde_beta, X, lambda, K1, m, K0, penalty, tau, eta, alpha, gamma, eps, max_iter, dfmax, gmax, user) {
    .Call(`_BRIGHT_gdfit_gaussian`, XtY, tilde_beta, X, lambda, K1, m, K0, penalty, tau, eta, alpha, gamma, eps, max_iter, dfmax, gmax, user)
}

rcpp_hello_world <- function() {
    .Call(`_BRIGHT_rcpp_hello_world`)
}

